"pageType": "maxi", "title": "Mintibuch | Abc | Seite 6", "version": "4.0.3", "classroomPageType": "maxi", "switchType": true}; var _this; var pageType = pageContent.pageType; var MintibuchPage = { Config: Minti.GetConfig({ title: pageContent.title, version: pageContent.version, }), Assets: { baseURL: pageContent.baseURL, image: { place: 'place.png', sound: 'sound.png', }, audio: { instruction: 'instruction.mp3', }, }, }; var assetURL = pageContent.baseURL.replace(pageContent.slug, 'assets'); for (var i = 0; i < pageContent.data.alphabet.length; i++) { var letter = pageContent.data.alphabet[i]; MintibuchPage.Assets.image['lower/' + letter] = assetURL + 'lower/' + letter + '.png'; MintibuchPage.Assets.image['upper/' + letter] = assetURL + 'upper/' + letter + '.png'; MintibuchPage.Assets.audio['sound/' + letter] = assetURL + 'sound/' + letter + '.mp3'; } var PlayScene = new Phaser.Class({
    Extends: Minti.Scene, _create: function () { _this = this; this.headers = pageContent.data.headers; this.data = pageContent.data.data; this.alphabet = pageContent.data.alphabet; this.limit = this.alphabet.length; this.addInstruction(pageType, App.prod, this.onStart); }, onStart: function () {
        this.add.image(this.centerX, this.centerY, 'place'); var alpha = this.alphabet.slice(); this.draggables = this.add.container(); for (var i = 0; i < this.alphabet.length; i++) { var datum = Minti.Utils.RemoveRandomItem(this.data); var letter = this.make.image({ x: datum[0], y: datum[1], key: 'lower/' + Minti.Utils.RemoveRandomItem(alpha), scale: 0, }); Minti.Buttonify(letter, true).on(Phaser.Input.Events.DRAG_END, this.onDragEnd).disableInteractive(); this.tweens.add({ targets: letter, scale: .5, ease: 'Back', duration: 400, delay: ((i * 50) + Math.random() * 100) }); this.draggables.add(letter); }

        setTimeout(function () { _this.addQuestion(); }, 1000);
    }, addQuestion: function () { if (this.question) { this.question.destroy(true); } this.question = this.add.container(this.centerX, this.centerY).setScale(0); var random = Minti.Utils.RemoveRandomItem(this.alphabet); var letter = this.add.image(0, 0, 'upper/' + random); var sound = this.add.image(-230, -180, 'sound').setScale(.4).setOrigin(0); Minti.Buttonify(sound, function () { this.scene.sound.stopAll(); this.scene.sound.play('sound/' + random); if (!this.scene.draggables.first.input.enabled) { Phaser.Actions.Call(this.scene.draggables.list, function (child) { child.setInteractive(); }); } }); this.question._data = random; this.question.add([letter, sound]).setSize(letter.displayWidth, letter.displayHeight); this.children.bringToTop(this.draggables); this.children.bringToTop(this.particles); this.tweens.add({ targets: this.question, scale: 1, ease: 'Back', duration: 500 }); }, onDragEnd: function () { var scene = this.scene; var hit = false, wrongSound = false; scene.sound.stopAll(); if (Minti.CheckOverlap(this, scene.question)) { if (this.texture.key === 'lower/' + scene.question._data) { hit = true; this.destroy(); scene.question.last.disableInteractive(); Minti.CloseButton(scene.draggables.list, 1); scene.counter++; scene.correctAnswer(scene.question.x, scene.question.y); if (scene.counter < scene.limit) { scene.ds.once(Phaser.Sound.Events.COMPLETE, scene.addQuestion, scene); } else { scene._endPage(); } } else { wrongSound = true; } } if (!hit) { scene.tweens.add({ targets: this, x: this.defaultPosition.x, y: this.defaultPosition.y, ease: 'Back', duration: 350 }); if (wrongSound) { scene.wrongAnswer(); } } },
}); var core = new Phaser.Game(MintibuchPage.Config); core.scene.add('PreloadScene', new Minti.PreloadScene, true, { nextScene: 'PlayScene', pageType: pageContent.pageType, Assets: MintibuchPage.Assets }); core.scene.add('PlayScene', PlayScene);

events.$emit('game', core); }Minti.AddTypeSwitch();, "jsList": [], "jsTemp": null, "name": "f9kjj7luS6D", "pageType": "maxi", "video": null, "module": null, "olympics": false, "pdf": null, "content_type": "ContentPages", "breadcrumb": [{ "id": 0, "name": "Home", "url": "\/kids\/home" }, { "id": 2710, "name": "Mintibuch", "url": "\/kids\/mintibuch", "lang_text": null }, { "id": 2718, "name": "ABC", "url": "\/kids\/mintibuch\/abc", "lang_text": null }, { "id": 1365, "name": "Seite 6", "url": "\/kids\/mintibuch\/abc\/seite-6" }], "next": "\/kids\/mintibuch\/abc\/seite-7", "prev": "\/kids\/mintibuch\/abc\/seite-5"}, "url": "\/kids\/mintibuch\/abc\/seite-6", "version": "838c6ff8f935809de52e0f86af29b5f5"
