@BASE_URL = http://localhost:3000/api

###

GET {{BASE_URL}}/users


###
POST {{BASE_URL}}/users
Content-Type: application/json

{
    "isim": "emre",
    "email": "okcu@gmail.com",
    "userName": "emreok",
    "sifre": "123456"
}

###
DELETE {{BASE_URL}}/users/671e2990e08833961e564b9
Content-Type: application/json

###
PATCH {{BASE_URL}}/users/671e2990e08833961e564b99
Content-Type: application/json

{

    "userName": "khsds"

}

###
POST  {{BASE_URL}}/users/giris
Content-Type: application/json

{
    "isim": "emre",
    "email": "okcwu@gmail.com",
    "userName": "emreok",
    "sifre": "3456"
}