@BASE_URL = http://localhost:3000/api

###

GET {{BASE_URL}}/users


###
POST {{BASE_URL}}/users
Content-Type: application/json

{
    "isim": "ddksdscdss",
    "email": "dei@d.c",
    "userName": "ddcdicds",
    "sifre": "43d5idscds7aa"
}

###
DELETE {{BASE_URL}}/users/671e2990e08833961e564b9
Content-Type: application/json

###
PATCH {{BASE_URL}}/users/6728b10fcbbb4d8a9f3eb3ea
Content-Type: application/json

{
    "isim": "kakash",
    "userName": "kakash",
    "email": "dertmii@gmail.com",
    "createdAt": "2024-10-27T12:46:58.855+00:00"
}