@BASE_URL = http://localhost:3000/api

###

GET {{BASE_URL}}/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzMxZTQ0MDIxYTE5YmExZTMwOTczZjQiLCJpYXQiOjE3MzIyNzg4NTMsImV4cCI6MTczMjI4MjQ1M30.XqP42ZBxi_YpAJpvPRy5Dj05eseuTufkly00LSNbaaA


###
POST {{BASE_URL}}/users
Content-Type: application/json

{
    "isim": "emreler11",
    "email": "okculer11@gmail.com",
    "userName": "e",
    "sifre": "1234561"
}

###
DELETE {{BASE_URL}}/users/671e2990e08833961e564b9
Content-Type: application/json

###
PATCH {{BASE_URL}}/users/6731e4f021a19ba1e30973f9
Content-Type: application/json

{

    "isim": "emreler2",
    "userName": "emreokler2"

}

###
POST  {{BASE_URL}}/users/giris
Content-Type: application/json

{
    "isim": "emreler",
    "email": "okculer@gmail.com",
    "userName": "emreokler",
    "sifre": "123456"
}

###
PATCH {{BASE_URL}}/users/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzMxZTQ0MDIxYTE5YmExZTMwOTczZjQiLCJpYXQiOjE3MzIyNzg4NTMsImV4cCI6MTczMjI4MjQ1M30.XqP42ZBxi_YpAJpvPRy5Dj05eseuTufkly00LSNbaaA

{

    "isim": "emre"

}


###
DELETE  {{BASE_URL}}/users/6731e4f021a19ba1e30973f9
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzMxZTQ0MDIxYTE5YmExZTMwOTczZjQiLCJpYXQiOjE3MzIyNzg4NTMsImV4cCI6MTczMjI4MjQ1M30.XqP42ZBxi_YpAJpvPRy5Dj05eseuTufkly00LSNbaaA

###
GET  {{BASE_URL}}/users/deleteAll
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzJjN2FmNDVmOWE5NTdhMTkxMTA4ZmEiLCJpYXQiOjE3MzA5NzgwNTksImV4cCI6MTczMDk4MTY1OX0.-O1U97kVA0QOq-sOmP-K9X_Ykpk-2TI8Q0PRkI089K4

###
DELETE {{BASE_URL}}/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzJjN2FmNDVmOWE5NTdhMTkxMTA4ZmEiLCJpYXQiOjE3MzA5NzgwNTksImV4cCI6MTczMDk4MTY1OX0.-O1U97kVA0QOq-sOmP-K9X_Ykpk-2TI8Q0PRkI089K4